### PR TITLE
Add functionality to reload modules only & Add shortcuts

### PR DESCRIPTION
**Pull request by markusstephanides**
I added a quick functionality that let's users build the modules in their IDEs and then let UnrealSharp only weave and reload the modules instead of building them. This allows me to handle any errors of my code inside my IDE and let UnrealSharp only do the reload work when it's actually needed.

I also added two shortcuts so compiling & reloading can be accessed quickly.

If that change is ok I would also go ahead and implement automatic reloading if the module files changed to complete this additional workflow.

### CODE REVIEW

**Comment by OlssonDev** [comment]
Finally could check it out! :D 

Nice feature! I'd love to see the shortcuts working.

**Comment by markusstephanides** [comment]
Thanks, will look into why they are not working!

**Comment by markusstephanides** [comment]
Shortcuts are fixed & added automatic reloading when modules were changed

**Comment by CadeEvs** [comment]
Testing it right now and it looks like when AutomaticHotReloading is set to "OnModuleChange" it will hot reload twice. Once on module change and also when the editor gains focus

**Comment by CadeEvs** [comment]
Just took a look. It looks like it triggers StartHotReload twice. Both stemming from OnCSharpCodeModified and due to the same managed dll. I also only have one project

**Comment by markusstephanides** [comment]
Does it trigger twice immediately or with some time in between or directly after each other?

**Comment by markusstephanides** [comment]
Stupid me, forgot to set the param for `StartHotReload` so it only reloads and not rebuild. Can you check again and let me know if it works now?

**Comment by CadeEvs** [comment]
Works now! Great work

**Pull request merged**
